-- Connecting a second customer to an already-managed Meta ad account (same
-- Business Portfolio, a different campaign under it) hit a global UNIQUE on
-- ad_accounts.meta_ad_account_id — one Meta ad account could only ever back
-- ONE of our customers, even though real Meta accounts commonly run several
-- campaigns for several purposes under one business.
--
-- Verified safe before writing this: every ownership/lookup query in the
-- codebase scopes by connection_id, never by meta_ad_account_id alone
-- (connection-store.ts, builder/session.ts, additions/session.ts,
-- customer-overview.ts) — so two customers, each with their OWN
-- meta_connections row, each with their OWN ad_accounts row pointing at the
-- same real Meta account, never collide. One-managed-campaign-per-customer
-- (managed_campaigns.customer_id UNIQUE, migration 004) is untouched.
--
-- Constraint name confirmed against the live DB (auto-generated by Postgres
-- for the original inline UNIQUE in migration 003).
ALTER TABLE ad_accounts DROP CONSTRAINT ad_accounts_meta_ad_account_id_key;
ALTER TABLE ad_accounts ADD CONSTRAINT ad_accounts_connection_meta_account_key
  UNIQUE (connection_id, meta_ad_account_id);
