// All user-facing copy lives here — never hard-code Hebrew inside a component.
// (The static landing page is the one exception; its copy lives in landing/.)
export const strings = {
  he: {
    appName: "AI Campaigner",
    tagline:
      "מנהלים לכם את הפרסום במטא — בלי ריטיינר של אלפי שקלים. עוקבים, מנתחים וממליצים; כל שינוי בתקציב או בקמפיין מתבצע רק באישור שלכם.",

    // Internal admin dogfood readout (AIC-7). The reference the customer Home
    // (P0.5) later mirrors, so labels are already in Hebrew.
    admin: {
      readoutTitle: "ביצועי הקמפיין",
      status: "סטטוס",
      spend: "הוצאה",
      leads: "פניות",
      cpl: "עלות לפנייה",
      vsPrevious: "מול התקופה הקודמת",
      perCreative: "לפי מודעה",
      creative: "מודעה",
      noData: "—",
      noCampaigns: "אין עדיין קמפיין מנוהל עם נתונים.",
      loading: "טוען…",
    },

    // Ops console (P0.4)
    ops: {
      title: "קונסולת תפעול",
      customers: "לקוחות",
      queue: "דורש טיפול",
      business: "עסק",
      connection: "חיבור",
      campaign: "קמפיין",
      subscription: "מנוי",
      budget: "תקציב",
      openRecs: "המלצות פתוחות",
      none: "אין",
      claim: "לקיחה לטיפול",
      resolve: "סגירה",
      review: "בדיקת קמפיין ראשונה",
      approve: "אישור",
      requestChanges: "בקשת שינויים",
      unsupported: "לא נתמך",
      billing: "חיוב",
      leadQuality: "איכות פניות",
      empty: "הרשימה ריקה.",
    },

    // Admin console shell + nav (AIC-43)
    adminShell: {
      brand: "AdPilot",
      brandSub: "ניהול",
      navOverview: "סקירה כללית",
      navCustomers: "לקוחות",
      navMeta: "נתוני Meta",
      navRecs: "המלצות",
      navOperators: "מפעילים",
      comingSoon: "בקרוב",
      logout: "יציאה",
      searchPlaceholder: "חיפוש לקוח או קמפיין…",
      searchNoResults: "לא נמצאו תוצאות.",
    },

    // Fleet-wide overview (AIC-43) — the operator's landing snapshot.
    fleet: {
      title: "סקירה כללית",
      subtitle: "מצב כל התיק במבט אחד.",
      campaignsByStatus: "קמפיינים לפי סטטוס",
      delivering: "מתפרסמים",
      needsAttention: "דורשים טיפול",
      spendThisPeriod: "הוצאה בתקופה הנוכחית",
      leadsThisPeriod: "פניות בתקופה הנוכחית",
      openQueue: "פריטים פתוחים בתור",
      viewQueue: "למעבר לתור",
      billingTitle: "לקוחות משלמים",
      realCustomers: "לקוחות אמיתיים",
      setupPaid: "שילמו הקמה",
      subscribed: "מנויים פעילים",
      conversionRate: "שיעור המרה",
      noRealCustomers: "אין עדיין לקוחות משלמים אמיתיים — התיק כרגע כולל רק חשבונות פנימיים/דוגמנות.",
      viewCustomers: "לצפייה בלקוחות",
      statusLabels: {
        under_review: "בבדיקה",
        active: "פעיל",
        paused: "מושהה",
        needs_attention: "דורש טיפול",
        connection_problem: "בעיית חיבור",
        unmanaged: "לא מנוהל",
      },
    },

    // Customer app (P0.5). All screen copy lives here — never hard-code Hebrew in
    // a component. Frontend built on mock data; backend wiring lands per ticket.
    app: {
      brandTag: "ניהול קמפיינים פשוט יותר לעסקים קטנים.",
      talkWa: "דברו איתנו בוואטסאפ",
      talk: "דברו איתנו",
      back: "חזרה",
      save: "שמירה",
      approve: "אישור",
      notNow: "לא עכשיו",
      help: "עזרה",
      logout: "יציאה",
      loading: "טוען…",
      loadError: "לא הצלחנו לטעון את הנתונים.",
      retry: "לניסיון חוזר",
      nav: { sectionManage: "ניהול", sectionHelp: "עזרה", menu: "תפריט" },
      auth: {
        signupTitle: "פותחים חשבון ומתחילים",
        signupSub: "אחרי ההרשמה נקבע שיחת היכרות קצרה ונתחיל בהקמה.",
        name: "שם מלא",
        email: "אימייל",
        password: "סיסמה",
        terms: "אני מאשר/ת את תנאי השירות ואת מדיניות הפרטיות.",
        createAccount: "יצירת חשבון",
        haveAccount: "כבר יש לכם חשבון?",
        login: "כניסה",
        loginTitle: "ברוכים שחזרתם",
        loginSub: "הקמפיין ממשיך לעבוד גם כשאתם לא כאן.",
        forgotLink: "שכחתי סיסמה",
        noAccount: "אין לכם עדיין חשבון?",
        signup: "הרשמה",
        forgotTitle: "איפוס סיסמה",
        forgotSub: "הזינו את כתובת המייל ונשלח לכם קישור לאיפוס.",
        sendLink: "שלחו לי קישור",
        backToLogin: "← חזרה לכניסה",
        forgotSentTitle: "שלחנו קישור",
        forgotSent: "הקישור תקף לשעה. לא הגיע? בדקו בספאם או שלחו שוב.",
        resend: "שליחה חוזרת",
        resetTitle: "סיסמה חדשה",
        resetSub: "בחרו סיסמה חדשה לחשבון.",
        savePassword: "שמירת הסיסמה",
        resetDoneTitle: "הסיסמה עודכנה.",
        resetDoneSub: "אפשר להיכנס לחשבון עם הסיסמה החדשה.",
        loginToAccount: "כניסה לחשבון",
        preQuestion: "יש שאלה לפני שמתחילים?",
        afterSignup: "מה קורה אחרי ההרשמה",
        steps: ["שיחת היכרות עם בן אדם", "חיבור חשבון הפרסום", "אנחנו מתחילים לנהל"],
        previewNote: "אנחנו עוקבים אחרי הקמפיין, מציעים שיפורים ומבצעים רק מה שאישרתם.",
      },
      checkout: {
        title: "מצטרפים לניהול הקמפיין",
        sub: "תוכנית אחת, מחיר אחד. אחרי התשלום נקבע את שיחת ההיכרות.",
        plan: "התוכנית",
        perMonth: "לחודש",
        setupOnce: "הקמה חד־פעמית",
        metaNote: "תקציב הפרסום עצמו משולם ישירות למטא ואינו כלול במחיר.",
        included: "מה כלול",
        includes: ["ניהול קמפיין אחד", "מעקב שוטף", "המלצות לשיפור", "ביצוע שינויים שאישרתם", "תמיכה בוואטסאפ", "שיחות כשצריך"],
        payDetails: "פרטי תשלום",
        payNow: "לתשלום עכשיו",
        firstCharge: "הקמה + חודש ראשון",
        proceed: "המשך לתשלום",
        cancelNote: "אפשר לבטל את השירות בהתאם לתנאי השירות.",
        payQuestion: "שאלה על התשלום?",
      },
      onboarding: {
        eyebrow: "סטטוס ההקמה",
        greeting: "אנחנו מקימים את הניהול",
        greetingHi: "שלום",
        steps: ["החשבון נפתח", "שיחת היכרות", "חיבור Meta", "בדיקת הקמפיין", "מוכנים לניהול"],
        done: "הושלם",
        now: "עכשיו",
        later: "בהמשך",
        needHelpTitle: "צריכים עזרה?",
        needHelp: "אנחנו כאן. אפשר לכתוב לנו בוואטסאפ ונעבור על זה יחד.",
        callTitle: "מתחילים בשיחת היכרות",
        callSub: "נכיר את העסק, נעבור על הקמפיין הקיים ונעזור לחבר את חשבון Meta.",
        bookCall: "קביעת שיחה",
        bookedTitle: "השיחה שלכם נקבעה",
        bookedBadge: "נקבעה שיחה",
        date: "תאריך", time: "שעה", length: "אורך", how: "איך",
        bookedNote: "בשיחה נעבור יחד על העסק ועל הקמפיין הקיים.",
        reschedule: "שינוי מועד",
        connectTitle: "עכשיו מחברים את חשבון Meta",
        connectSub: "כדי שנוכל לעקוב ולנהל את הקמפיין, צריך לתת לנו גישה לחשבון הפרסום.",
        connectCta: "לחיבור Meta",
        connectHelp: "צריכים עזרה? נעשה את זה יחד בשיחה.",
        reviewBadge: "בתהליך",
        reviewTitle: "אנחנו עוברים על הקמפיין",
        reviewSub: "בודקים שהמבנה, התקציב והמודעות מתאימים לניהול דרך השירות.",
        metaConnected: "חשבון Meta מחובר",
        campaignFound: "הקמפיין נמצא",
        inReview: "בבדיקה",
        nothingToDo: "אין צורך לעשות דבר כרגע.",
        approveBadge: "מחכים לכם",
        approveTitle: "צריך אישור קטן לפני שמתחילים",
        approveSub: "עברנו על הקמפיין וממליצים לעצור מודעה אחת ולהשאיר את התקציב על ₪80 ביום. צריך את האישור שלכם כדי לבצע.",
        viewChange: "לצפייה בשינוי",
        wantToTalk: "אני רוצה לדבר על זה",
        readyTitle: "הכל מוכן",
        readySub: "הקמפיין מחובר ואנחנו מתחילים לעקוב אחריו.",
        goToAccount: "מעבר לחשבון",
      },
      connect: {
        backToStatus: "← חזרה לסטטוס ההקמה",
        title: "חיבור חשבון Meta",
        sub: "צריך לתת לנו גישה לחשבון הפרסום שבו נמצא הקמפיין שננהל.",
        noPassword: "אנחנו לא צריכים את הסיסמה שלכם לפייסבוק.",
        howTitle: "איך עושים את זה",
        steps: [
          "פותחים את הגדרות העסק ב־Meta",
          "מוסיפים את AdPilot כשותף עסקי",
          "נותנים גישה לחשבון הפרסום",
          "אם נדרש, נותנים גישה גם לעמוד הפייסבוק / אינסטגרם",
          "חוזרים לכאן ואנחנו בודקים שהכול מחובר",
        ],
        openMeta: "פתיחת Meta Business Settings ↗",
        businessId: "BUSINESS ID",
        copy: "העתקה",
        copied: "הועתק",
        whenNeeded: "מתי זה נדרש?",
        whenNeededBody: "אם המודעות מוצגות מהעמוד או מהאינסטגרם שלכם, נצטרך גם אותם כדי לפרסם ולעצור מודעות.",
        checkCta: "בדיקת החיבור",
        checking: "בודקים את החיבור…",
        checkingSub: "זה לוקח כמה שניות. אפשר להישאר בעמוד.",
        connectedTitle: "החשבון מחובר",
        adAccount: "חשבון פרסום", fbPage: "עמוד פייסבוק", instagram: "אינסטגרם",
        technical: "פרטים טכניים",
        continue: "המשך",
        missingTitle: "חסרה גישה",
        missingBody: "חשבון הפרסום מחובר, אבל חסרה גישה לעמוד הפייסבוק. בלי גישה לעמוד לא נוכל לפרסם או לעצור מודעות בשמכם. זה תיקון קצר בהגדרות העסק ב־Meta.",
        connected: "מחובר", missing: "חסר",
        howToFix: "איך מתקנים?",
        fixSteps: [
          "בהגדרות העסק ב־Meta עוברים ל״עמודים״.",
          "בוחרים את העמוד ולוחצים על ״שותפים״.",
          "מוסיפים את AdPilot עם הרשאת ניהול מודעות.",
        ],
        recheck: "בדיקה מחדש",
        notVerifiedTitle: "לא הצלחנו לאמת את החיבור",
        notVerifiedBody: "אפשר לנסות שוב או לדבר איתנו ונעבור על זה יחד. הקמפיין שלכם ממשיך לרוץ כרגיל בזמן הזה.",
        retry: "נסה שוב",
      },
      review: {
        title: "אנחנו ממליצים על כמה התאמות לפני שמתחילים",
        sub: "זה הקמפיין שננהל. עברנו עליו וכתבנו מה כדאי לשנות — הכל יבוצע רק אחרי שתאשרו.",
        campaign: "קמפיין WhatsApp", active: "פעיל",
        budget: "תקציב", area: "אזור", ads: "מודעות", goal: "מטרה",
        budgetVal: "₪80 ביום", areaVal: "ראשון לציון והסביבה", adsVal: "4 מודעות", goalVal: "פניות ב־WhatsApp",
        running: "המודעות שרצות",
        keep: "נשארת", pauseRec: "מומלץ לעצור", isNew: "חדשה",
        proposalsTitle: "מה אנחנו מציעים",
        proposals: [
          { t: "לעצור מודעה אחת", d: "המודעה הזאת כמעט לא מביאה פניות לעומת האחרות." },
          { t: "לפשט את מבנה הקמפיין", d: "הקמפיין הקיים מפוצל למספר קבוצות שלא נותנות מספיק מידע בתקציב הנוכחי." },
          { t: "להישאר על ₪80 ביום", d: "התקציב המקסימלי לאחר השינוי: ₪80 ביום." },
        ],
        approveStart: "מאשר להתחיל",
        confirmedTitle: "קיבלנו את האישור",
        confirmedSub: "אנחנו משלימים את ההגדרה ומתחילים לעקוב.",
        backToStatus: "חזרה לסטטוס ההקמה",
      },
      home: {
        title: "הקמפיין שלך",
        navHome: "ראשי", navRecs: "המלצות", navSettings: "עזרה והגדרות",
        periods: { month: "החודש", days7: "7 ימים", prev: "חודש קודם" },
        kpiCpl: "לפנייה", kpiLeads: "פניות", kpiSpend: "הוצאה החודש",
        states: {
          ok: { badge: "פעיל", title: "הכל עובד כרגיל", body: "הקמפיין פעיל ואין כרגע משהו שדורש את תשומת הלב שלך." },
          rec: { badge: "מחכה לך", title: "יש לנו המלצה אחת", body: "מצאנו שינוי שיכול לשפר את הקמפיין ומחכה לאישור שלך.", cta: "לצפייה בהמלצה" },
          collecting: { badge: "אוספים נתונים", title: "רק התחלנו לאסוף נתונים", body: "עדיין מוקדם להסיק מסקנות. אנחנו ממשיכים לעקוב." },
          paused: { badge: "מושהה", title: "הקמפיין כרגע מושהה", body: "הקמפיין מושהה ואינו מוציא תקציב או מביא פניות עד שנחזיר אותו לפעילות. לחידוש הפעילות דברו איתנו.", cta: "" },
          attention: { badge: "צריך טיפול", title: "איבדנו גישה לחשבון Meta", body: "הקמפיין עשוי להמשיך לרוץ, אבל לא נוכל לנהל אותו עד לחיבור מחדש.", cta: "חיבור מחדש" },
          setup: { badge: "בהקמה", title: "אנחנו מקימים את החשבון", body: "החשבון נפתח. אחרי שיחת ההיכרות וחיבור Meta נתחיל לנהל את הקמפיין ותוכלו לראות כאן נתונים.", cta: "לסטטוס ההקמה" },
          // AIC-39: a not-delivering ad set — distinct from a lost Meta connection.
          delivery: { badge: "צריך טיפול", title: "חלק מהקמפיין לא מתפרסם כרגע", body: "אחת מקבוצות הפרסום נתקלה בבעיה ואינה מציגה מודעות. אנחנו כבר על זה — ניצור קשר אם נצטרך משהו מכם. שאר הקמפיין ממשיך לרוץ.", cta: "" },
        },
        live: {
          vsPrev: "מהתקופה הקודמת",
          noCompare: "אין תקופה קודמת להשוואה",
          noActivity: "עדיין לא בוצעו שינויים בקמפיין.",
          adsActive: "מודעות פעילות",
          perDay: "ביום",
          perMonth: "בחודש",
          none: "—",
          automated: "בוצע אוטומטית",
          byUs: "בוצע על ידינו",
        },
        // AIC-37: opt-in per-audience / per-creative details — collapsed by
        // default, never the landing view.
        details: {
          show: "הצג פירוט",
          hide: "הסתר פירוט",
          empty: "עדיין אין מספיק נתונים לפירוט לפי קהל.",
          audienceCol: "קהל",
          spendCol: "הוצאה",
          leadsCol: "פניות",
          cplCol: "עלות לפנייה",
          creativesCol: "מודעות",
        },
        recWaitingTitle: "המלצה שמחכה לך",
        recWaiting: "כדאי לעצור את אחת המודעות",
        recWaitingReason: "היא הוציאה ₪184 והביאה פנייה אחת בלבד. שתי המודעות האחרות עובדות טוב יותר.",
        viewApprove: "לצפייה ולאישור",
        noActionTitle: "אין כרגע משהו שצריך לעשות",
        noAction: "אנחנו ממשיכים לעקוב אחר הקמפיין.",
        weeklyTitle: "משוב שבועי",
        weeklyQ: "איך היו הפניות השבוע?",
        weeklyCount: "כמה מהפניות שקיבלת השבוע היו רלוונטיות?",
        weeklyLeadsLine: "פניות השבוע",
        weeklyThanksTitle: "קיבלנו, תודה",
        weeklyThanks: "זה עוזר לנו להבין טוב יותר אילו פניות באמת שוות לעסק.",
        weeklyNoLeads: "השבוע עדיין לא התקבלו פניות. אנחנו ממשיכים לעקוב לפני שממליצים על שינוי.",
        recentTitle: "מה קרה לאחרונה", recentAll: "לכל השינויים",
        recent: [
          { d: "12 באוג׳", t: "עצרנו מודעה חלשה לאחר שאישרתם." },
          { d: "5 באוג׳", t: "התקציב עודכן מ־₪70 ל־₪80 ביום." },
          { d: "1 באוג׳", t: "התחיל ניהול הקמפיין." },
        ],
        summaryTitle: "קמפיין WhatsApp",
        sMode: "מצב", sBudget: "תקציב", sAds: "מודעות", sLeads: "פניות לפי שבוע",
        sBudgetVal: "₪80 ביום", sAdsVal: "4 מודעות פעילות", sLeadsVal: "18 סה״כ",
      },
      recs: {
        title: "המלצות",
        emptyTitle: "אין עדיין המלצות",
        empty: "אנחנו ממשיכים לעקוב אחרי הקמפיין ונעדכן כשיהיה משהו ששווה לשנות.",
        waiting: "מחכה לאישור שלך",
        view: "לצפייה",
        doneTitle: "מה כבר עשינו",
        notSure: "לא בטוחים לגבי המלצה?",
      },
      recDetail: {
        back: "← חזרה להמלצות",
        createdAgo: "נוצרה לפני 2 ימים",
        pauseTitle: "כדאי לעצור את המודעה הזאת",
        whyTitle: "למה אנחנו ממליצים",
        pauseWhy: "המודעה הוציאה ₪184 ב־7 הימים האחרונים והביאה פנייה אחת. שתי המודעות האחרות מביאות פניות במחיר נמוך משמעותית.",
        whatChangesTitle: "מה ישתנה?",
        pauseChanges: ["המודעה הזאת תיעצר.", "הקמפיין ושאר המודעות ימשיכו לפעול.", "התקציב הכולל לא יגדל."],
        incTitle: "כדאי להגדיל מעט את התקציב",
        incWhy: "מחיר הפנייה נמוך מהיעד כבר מספר ימים ואנחנו רואים מקום להגדיל את הפעילות.",
        today: "היום", proposed: "מוצע",
        incFrom: "₪70 ביום", incTo: "₪80 ביום",
        maxImpact: "תוספת מקסימלית של ₪10 ביום.",
        incChange: "התקציב יעבור מ־₪70 ל־₪80 ביום. השינוי מתבצע מיד לאחר האישור.",
        replaceTitle: "הגיע הזמן להחליף מודעה",
        replaceWhy: "הביצועים שלה נחלשו משמעותית בשבוע האחרון.",
        replaceNote: "נבקש ממך קריאייטיב חדש לפני שנבצע שינוי.",
        wantToTalk: "רוצה לדבר על זה?",
        approvedTitle: "אישרתם את השינוי",
        approvedSub: "אנחנו מבצעים אותו עכשיו. נעדכן כאן כשזה יושלם.",
        executedTitle: "השינוי בוצע",
        whatWeDid: "מה נעשה", whenDone: "מתי",
        backToRecs: "חזרה להמלצות",
        dismissedTitle: "בחרתם לא לבצע את השינוי",
        dismissedSub: "הקמפיין ממשיך כרגיל. אם תשנו את דעתכם, אנחנו כאן.",
        expiredTitle: "ההמלצה כבר לא רלוונטית",
        expiredSub: "מאז שיצרנו אותה, ביצועי הקמפיין השתנו. אם נראה שוב מקום לשינוי, נעדכן.",
        failedTitle: "לא הצלחנו לבצע את השינוי",
        failedSub: "לא בוצע שינוי בקמפיין. אנחנו בודקים מה קרה ונחזור אליכם.",
        heldTitle: "השינוי לא בוצע כרגע",
        heldSub: "לא בוצע שינוי בקמפיין. אפשר לנסות שוב מאוחר יותר או לדבר איתנו.",
        unavailableSub: "השירות זמנית אינו זמין לביצוע שינויים. נסו שוב עוד מעט.",
        // Titles + "what changes" keyed by recommendation type (live data path).
        titles: {
          pause_creative: "כדאי לעצור את המודעה הזאת",
          pause_adset: "כדאי לעצור קהל שמבזבז תקציב",
          increase_budget: "כדאי להגדיל מעט את התקציב",
          decrease_budget: "כדאי להוריד זמנית את התקציב",
          replace_creative: "כדאי להחליף את הקריאייטיב",
          no_action: "אין כרגע שינוי מומלץ",
        },
        changesBudget: "השינוי מתבצע מיד לאחר האישור.",
        changesReplace: "החלפת הקריאייטיב מתבצעת יחד עם הצוות שלנו — ניצור קשר להמשך.",
        changesAudience: "הקהל הזה ייעצר; התקציב יופנה לקהל שמביא תוצאות טובות יותר. סך התקציב לא יגדל.",
        maxImpactPrefix: "תוספת מקסימלית של",
      },
      settings: {
        title: "עזרה והגדרות",
        supportTitle: "צריכים עזרה?",
        support: "אפשר לדבר איתנו בוואטסאפ או לקבוע שיחה.",
        bookCall: "קביעת שיחה",
        budgetTitle: "תקציב פרסום",
        budgetReq: "בקשה לשינוי תקציב",
        budgetNote: "זהו התקציב של Meta ואינו כולל את דמי השירות.",
        metaTitle: "Meta",
        checkConn: "בדיקת חיבור",
        planTitle: "המסלול שלך",
        planLine: "ניהול קמפיין אחד",
        setupPaid: "ההקמה שולמה",
        nextCharge: "החיוב הבא", nextChargeVal: "1 בספטמבר 2026",
        payMethod: "אמצעי תשלום", payMethodVal: "Visa •••• 4417",
        payMethodManual: "חיוב ידני מול הצוות",
        setupPending: "ההקמה בתשלום",
        noSubTitle: "אין מנוי פעיל",
        noSubNote: "זהו חשבון ניהול פנימי. פרטי המסלול יופיעו כאן לאחר הצטרפות.",
        managePay: "ניהול תשלום",
        budgetReqSent: "בקשתך התקבלה. ניצור איתך קשר בקרוב.",
        checking: "בודקים את החיבור…",
        connOk: "החיבור תקין",
        connProblem: "יש בעיה בחיבור — נחזור אליך.",
        pwCurrent: "סיסמה נוכחית", pwNew: "סיסמה חדשה (לפחות 8 תווים)",
        pwSave: "עדכון סיסמה", pwCancel: "ביטול",
        pwDone: "הסיסמה עודכנה.",
        pwWrong: "הסיסמה הנוכחית שגויה.",
        pwTooShort: "הסיסמה החדשה חייבת להכיל לפחות 8 תווים.",
        accountTitle: "החשבון",
        nameLabel: "שם", emailLabel: "אימייל", changePw: "שינוי סיסמה",
        cancelNote: "ביטול השירות מתבצע בשיחה איתנו, כדי שנוכל לסגור נכון את הקמפיין ב־Meta.",
        cancelLink: "דברו איתנו על ביטול",
      },
      mock: { userName: "לילך ברקוביץ'", userInitials: "לב", email: "lilach@studio.co.il", businessId: "418 552 907 431" },
    },

    // Connection health (AIC-5). Every non-ok state shows the same plain-Hebrew
    // reconnect message — the customer never sees Meta jargon like "revoked",
    // "invalid token", or "OAuth". The server sends the access_health value; the
    // client maps it to copy here.
    connection: {
      needsAttentionTitle: "חסרה לנו הרשאה לחשבון הפרסום",
      needsAttentionBody:
        "כדי שנוכל להמשיך לנהל את הקמפיין, צריך לחבר מחדש את חשבון הפרסום.",
      reconnectCta: "התחברות מחדש",
      healthyStatus: "החיבור לחשבון הפרסום תקין",
    },
  },
} as const;

// Map a connection's access_health to what the customer sees. Anything but "ok"
// is the same reconnect prompt — the distinction between revoked/invalid/
// needs_reconnect is internal only.
export function connectionMessage(
  accessHealth: "ok" | "revoked" | "invalid" | "needs_reconnect",
): { healthy: boolean; title: string; body?: string; cta?: string } {
  const c = strings.he.connection;
  if (accessHealth === "ok") {
    return { healthy: true, title: c.healthyStatus };
  }
  return {
    healthy: false,
    title: c.needsAttentionTitle,
    body: c.needsAttentionBody,
    cta: c.reconnectCta,
  };
}
