// All user-facing copy lives here — never hard-code Hebrew inside a component.
// (The static landing page is the one exception; its copy lives in landing/.)
export const strings = {
  he: {
    appName: "AI Campaigner",
    tagline:
      "מנהלים לכם את הפרסום במטא — בלי ריטיינר של אלפי שקלים. עוקבים, מנתחים וממליצים; כל שינוי בתקציב או בקמפיין מתבצע רק באישור שלכם.",

    // Internal admin dogfood readout (AIC-7). The reference the customer Home
    // (P0.5) later mirrors, so labels are already in Hebrew.
    admin: {
      readoutTitle: "ביצועי הקמפיין",
      status: "סטטוס",
      spend: "הוצאה",
      leads: "פניות",
      cpl: "עלות לפנייה",
      vsPrevious: "מול התקופה הקודמת",
      perCreative: "לפי מודעה",
      creative: "מודעה",
      noData: "—",
      noCampaigns: "אין עדיין קמפיין מנוהל עם נתונים.",
      loading: "טוען…",
    },

    // Ops console (P0.4)
    ops: {
      title: "קונסולת תפעול",
      customers: "לקוחות",
      queue: "דורש טיפול",
      business: "עסק",
      connection: "חיבור",
      campaign: "קמפיין",
      subscription: "מנוי",
      budget: "תקציב",
      openRecs: "המלצות פתוחות",
      none: "אין",
      claim: "לקיחה לטיפול",
      resolve: "סגירה",
      review: "בדיקת קמפיין ראשונה",
      approve: "אישור",
      requestChanges: "בקשת שינויים",
      unsupported: "לא נתמך",
      billing: "חיוב",
      leadQuality: "איכות פניות",
      empty: "הרשימה ריקה.",
      openMetaExplorer: "נתוני Meta המלאים ←",
    },

    // Admin console shell + nav (AIC-43)
    adminShell: {
      brand: "AdPilot",
      brandSub: "ניהול",
      navOverview: "סקירה כללית",
      navCustomers: "לקוחות",
      navMeta: "נתוני Meta",
      navRecs: "המלצות",
      navOperators: "מפעילים",
      comingSoon: "בקרוב",
      logout: "יציאה",
      searchPlaceholder: "חיפוש לקוח או קמפיין…",
      searchNoResults: "לא נמצאו תוצאות.",
    },

    // Customer CRUD (AIC-44) — create/edit/deactivate/delete, on the customers page.
    customerCrud: {
      newCustomer: "לקוח חדש",
      searchPlaceholder: "חיפוש לפי שם עסק או איש קשר…",
      filterAll: "הכל",
      filterActive: "פעילים",
      filterDeactivated: "מושבתים",
      noResults: "לא נמצאו לקוחות.",
      fieldBusinessName: "שם העסק",
      fieldCategory: "תחום",
      fieldMainService: "שירות עיקרי",
      fieldGeoArea: "אזור שירות",
      fieldPrimaryCustomer: "קהל היעד",
      fieldOffer: "הצעה",
      fieldContactName: "איש קשר",
      fieldContactPhone: "טלפון",
      fieldContactEmail: "אימייל",
      fieldIsTest: "חשבון פנימי/בדיקה (לא נספר בנתוני חיוב)",
      fieldAgreedBudget: "תקציב מוסכם (₪ ליום)",
      create: "יצירה",
      edit: "עריכה",
      save: "שמירה",
      cancel: "ביטול",
      saving: "שומר…",
      createError: "יצירת הלקוח נכשלה.",
      saveError: "השמירה נכשלה.",
      deactivate: "השבתה",
      reactivate: "הפעלה מחדש",
      deactivateConfirm: "להשבית את הלקוח? הקמפיין יסומן כלא מנוהל — המעקב וההפעלה ייעצרו. הפעולה הפיכה.",
      deactivatedBadge: "מושבת",
      deactivatedNote: "לקוח מושבת — הקמפיין מסומן כלא מנוהל. ניתן להפעיל מחדש.",
      reactivateNote: "הפעלה מחדש תבטל את סטטוס ההשבתה בלבד — ניהול הקמפיין בפועל מופעל בנפרד דרך פקדי הקמפיין.",
      deleteButton: "מחיקה סופית",
      deleteTitle: "מחיקת לקוח לצמיתות",
      deleteWarning:
        "פעולה זו מוחקת לצמיתות את הלקוח ואת כל הנתונים המקושרים אליו (מנוי, חיבור Meta, קמפיין מנוהל, המלצות, היסטוריית פעולות). היא אינה הפיכה. נכסי ה-Meta של הלקוח (חשבון פרסום, עמוד) לא יימחקו — רק ההרשאה שלנו לנהל אותם. במקרה הרגיל עדיף להשבית ולא למחוק.",
      deleteConfirmLabel: "הקלידו את שם העסק לאישור:",
      deleteConfirmMismatch: "השם שהוקלד אינו תואם.",
      confirmDelete: "מחיקה לצמיתות",
      auditTitle: "יומן פעולות",
      auditEmpty: "אין פעולות רשומות עדיין.",
      leadQualityWeek: "שבוע",
      leadQualityRelevant: "רלוונטיות",
      leadQualityWon: "לקוחות שנסגרו",
      historyTitle: "היסטוריית פעולות בקמפיין",
      historyAutomated: "(אוטומטי)",
      historyFailed: "· נכשל",
      auditActionLabels: {
        "customer.create": "נוצר",
        "customer.edit": "נערך",
        "customer.deactivate": "הושבת",
        "customer.reactivate": "הופעל מחדש",
        "customer.delete": "נמחק",
      } as Record<string, string>,
    },

    // Full Meta data explorer (AIC-45) — the unrestricted internal deep view.
    metaExplorer: {
      title: "נתוני Meta",
      subtitle: "העץ המלא כפי שמטא מדווח — כל מדד, כולל אלה שמוסתרים מהלקוח.",
      pickCampaign: "בחירת קמפיין",
      noCampaigns: "אין קמפיין מנוהל עדיין.",
      refresh: "רענון מ-Meta",
      refreshing: "מרענן…",
      fetchedAt: "נשלף",
      period: "תקופה",
      noMetaCampaign: "הקמפיין הזה עוד לא מקושר לקמפיין ב-Meta.",
      noToken: "החיבור ל-Meta אינו מוגדר כרגע — אי אפשר לשלוף נתונים חיים.",
      metaError: "שגיאה בשליפה מ-Meta:",
      campaignLevel: "רמת קמפיין",
      adSets: "קבוצות מודעות",
      ads: "מודעות",
      budget: "תקציב",
      dailyBudget: "תקציב יומי",
      lifetimeBudget: "תקציב כולל",
      bidStrategy: "אסטרטגיית הצעה",
      targeting: "טירגוט",
      age: "גיל",
      gender: "מגדר",
      geo: "אזור",
      interests: "תחומי עניין",
      issues: "בעיות",
      flexibleCreative: "קריאייטיב גמיש (דינמי)",
      flexibleImages: "תמונות",
      flexibleVideos: "סרטונים",
      flexibleBodies: "טקסטים",
      flexibleTitles: "כותרות",
      noCreative: "אין קריאייטיב מקושר.",
      metrics: {
        spend: "הוצאה", impressions: "חשיפות", reach: "הגעה", frequency: "תדירות",
        cpm: "CPM", ctr: "CTR", cpc: "CPC", leads: "פניות", cpl: "עלות לפנייה",
        qualityRanking: "דירוג איכות", engagementRateRanking: "דירוג מעורבות", conversionRateRanking: "דירוג המרה",
      },
      noAdSets: "אין קבוצות מודעות.",
      noAds: "אין מודעות.",
    },

    // Recommendations oversight (AIC-46) — every rec, every customer.
    recsOversight: {
      title: "המלצות",
      subtitle: "כל המלצה שהמנוע הפיק, בכל הלקוחות — הראיות והסטטוס המלא.",
      filterState: "סטטוס",
      filterType: "סוג",
      filterCustomer: "לקוח",
      all: "הכל",
      noResults: "אין המלצות התואמות את הסינון.",
      business: "לקוח",
      type: "סוג",
      state: "סטטוס",
      impact: "השפעה מקסימלית",
      created: "נוצרה",
      flagged: "מסומנת",
      evidence: "ראיות",
      rationale: "נימוק",
      currentBudget: "תקציב נוכחי",
      proposedBudget: "תקציב מוצע",
      approvedBy: "אושרה ע\"י",
      executedAt: "בוצעה",
      executionResult: "תוצאת ביצוע",
      viewActionHistory: "→ צפייה בהיסטוריית הפעולות של הלקוח",
      flagButton: "סימון לבדיקה",
      unflagButton: "ביטול סימון",
      flagNotePlaceholder: "למה זה נראה חשוד? (רשות)",
      flagNoteLabel: "הערת סימון",
      stateLabels: {
        proposed: "הוצעה", approved: "אושרה", executing: "בביצוע", executed: "בוצעה",
        failed: "נכשלה", dismissed: "נדחתה", expired: "פגה",
      } as Record<string, string>,
      typeLabels: {
        pause_creative: "עצירת מודעה", pause_adset: "עצירת קהל", increase_budget: "העלאת תקציב",
        decrease_budget: "הורדת תקציב", replace_creative: "החלפת קריאייטיב", no_action: "ללא פעולה",
      } as Record<string, string>,
    },

    // Operator accounts + admin action audit log (AIC-47).
    operators: {
      title: "מפעילים",
      subtitle: "מי יכול לגשת לקונסולה, ומה נעשה בה.",
      sectionOperators: "חשבונות מפעילים",
      sectionAudit: "יומן פעולות מלא",
      email: "אימייל",
      name: "שם",
      role: "תפקיד",
      created: "נוצר",
      roleFullAdmin: "מנהל מלא",
      roleOperator: "מפעיל",
      addOperator: "הוספת מפעיל",
      addEmailPlaceholder: "אימייל של משתמש קיים…",
      addNote: "אפשר להוסיף רק משתמש שכבר נרשם למערכת (אין עדיין שליחת הזמנות במייל).",
      add: "הוספה",
      addError: "ההוספה נכשלה — ודאו שהאימייל שייך למשתמש קיים ושאינו כבר מפעיל.",
      remove: "הסרת גישה",
      removeConfirm: "להסיר את הגישה לקונסולה? הכניסה של המשתמש למערכת עצמה לא נמחקת.",
      removeError: "ההסרה נכשלה.",
      roleChangeError: "שינוי התפקיד נכשל.",
      onlyFullAdminNote: "רק מנהל מלא יכול להוסיף, להסיר או לשנות תפקיד של מפעילים.",
      filterActor: "מפעיל",
      filterEntityType: "סוג ישות",
      all: "הכל",
      noEntries: "אין רשומות התואמות את הסינון.",
      entityTypeLabels: {
        customer: "לקוח", recommendation: "המלצה", operator: "מפעיל", campaign: "קמפיין",
      } as Record<string, string>,
    },

    // Fleet-wide overview (AIC-43) — the operator's landing snapshot.
    fleet: {
      title: "סקירה כללית",
      subtitle: "מצב כל התיק במבט אחד.",
      campaignsByStatus: "קמפיינים לפי סטטוס",
      delivering: "מתפרסמים",
      needsAttention: "דורשים טיפול",
      spendThisPeriod: "הוצאה בתקופה הנוכחית",
      leadsThisPeriod: "פניות בתקופה הנוכחית",
      openQueue: "פריטים פתוחים בתור",
      viewQueue: "למעבר לתור",
      billingTitle: "לקוחות משלמים",
      realCustomers: "לקוחות אמיתיים",
      setupPaid: "שילמו הקמה",
      subscribed: "מנויים פעילים",
      conversionRate: "שיעור המרה",
      noRealCustomers: "אין עדיין לקוחות משלמים אמיתיים — התיק כרגע כולל רק חשבונות פנימיים/דוגמנות.",
      viewCustomers: "לצפייה בלקוחות",
      statusLabels: {
        under_review: "בבדיקה",
        active: "פעיל",
        paused: "מושהה",
        needs_attention: "דורש טיפול",
        connection_problem: "בעיית חיבור",
        unmanaged: "לא מנוהל",
      },
    },

    // Customer app (P0.5). All screen copy lives here — never hard-code Hebrew in
    // a component. Frontend built on mock data; backend wiring lands per ticket.
    app: {
      brandTag: "ניהול קמפיינים פשוט יותר לעסקים קטנים.",
      talkWa: "דברו איתנו בוואטסאפ",
      talk: "דברו איתנו",
      back: "חזרה",
      save: "שמירה",
      approve: "אישור",
      notNow: "לא עכשיו",
      help: "עזרה",
      logout: "יציאה",
      loading: "טוען…",
      loadError: "לא הצלחנו לטעון את הנתונים.",
      retry: "לניסיון חוזר",
      nav: { sectionManage: "ניהול", sectionHelp: "עזרה", menu: "תפריט" },
      auth: {
        signupTitle: "פותחים חשבון ומתחילים",
        signupSub: "אחרי ההרשמה נקבע שיחת היכרות קצרה ונתחיל בהקמה.",
        name: "שם מלא",
        email: "אימייל",
        password: "סיסמה",
        terms: "אני מאשר/ת את תנאי השירות ואת מדיניות הפרטיות.",
        createAccount: "יצירת חשבון",
        haveAccount: "כבר יש לכם חשבון?",
        login: "כניסה",
        loginTitle: "ברוכים שחזרתם",
        loginSub: "הקמפיין ממשיך לעבוד גם כשאתם לא כאן.",
        forgotLink: "שכחתי סיסמה",
        noAccount: "אין לכם עדיין חשבון?",
        signup: "הרשמה",
        forgotTitle: "איפוס סיסמה",
        forgotSub: "הזינו את כתובת המייל ונשלח לכם קישור לאיפוס.",
        sendLink: "שלחו לי קישור",
        backToLogin: "← חזרה לכניסה",
        forgotSentTitle: "שלחנו קישור",
        forgotSent: "הקישור תקף לשעה. לא הגיע? בדקו בספאם או שלחו שוב.",
        resend: "שליחה חוזרת",
        resetTitle: "סיסמה חדשה",
        resetSub: "בחרו סיסמה חדשה לחשבון.",
        savePassword: "שמירת הסיסמה",
        resetDoneTitle: "הסיסמה עודכנה.",
        resetDoneSub: "אפשר להיכנס לחשבון עם הסיסמה החדשה.",
        loginToAccount: "כניסה לחשבון",
        preQuestion: "יש שאלה לפני שמתחילים?",
        afterSignup: "מה קורה אחרי ההרשמה",
        steps: ["שיחת היכרות עם בן אדם", "חיבור חשבון הפרסום", "אנחנו מתחילים לנהל"],
        previewNote: "אנחנו עוקבים אחרי הקמפיין, מציעים שיפורים ומבצעים רק מה שאישרתם.",
      },
      checkout: {
        title: "מצטרפים לניהול הקמפיין",
        sub: "תוכנית אחת, מחיר אחד. אחרי התשלום נקבע את שיחת ההיכרות.",
        plan: "התוכנית",
        perMonth: "לחודש",
        setupOnce: "הקמה חד־פעמית",
        metaNote: "תקציב הפרסום עצמו משולם ישירות למטא ואינו כלול במחיר.",
        included: "מה כלול",
        includes: ["ניהול קמפיין אחד", "מעקב שוטף", "המלצות לשיפור", "ביצוע שינויים שאישרתם", "תמיכה בוואטסאפ", "שיחות כשצריך"],
        payDetails: "פרטי תשלום",
        payNow: "לתשלום עכשיו",
        firstCharge: "הקמה + חודש ראשון",
        proceed: "המשך לתשלום",
        cancelNote: "אפשר לבטל את השירות בהתאם לתנאי השירות.",
        payQuestion: "שאלה על התשלום?",
      },
      onboarding: {
        eyebrow: "סטטוס ההקמה",
        greeting: "אנחנו מקימים את הניהול",
        greetingHi: "שלום",
        steps: ["החשבון נפתח", "שיחת היכרות", "חיבור Meta", "בדיקת הקמפיין", "מוכנים לניהול"],
        done: "הושלם",
        now: "עכשיו",
        later: "בהמשך",
        needHelpTitle: "צריכים עזרה?",
        needHelp: "אנחנו כאן. אפשר לכתוב לנו בוואטסאפ ונעבור על זה יחד.",
        callTitle: "מתחילים בשיחת היכרות",
        callSub: "נכיר את העסק, נעבור על הקמפיין הקיים ונעזור לחבר את חשבון Meta.",
        bookCall: "קביעת שיחה",
        bookedTitle: "השיחה שלכם נקבעה",
        bookedBadge: "נקבעה שיחה",
        date: "תאריך", time: "שעה", length: "אורך", how: "איך",
        bookedNote: "בשיחה נעבור יחד על העסק ועל הקמפיין הקיים.",
        reschedule: "שינוי מועד",
        connectTitle: "עכשיו מחברים את חשבון Meta",
        connectSub: "כדי שנוכל לעקוב ולנהל את הקמפיין, צריך לתת לנו גישה לחשבון הפרסום.",
        connectCta: "לחיבור Meta",
        connectHelp: "צריכים עזרה? נעשה את זה יחד בשיחה.",
        reviewBadge: "בתהליך",
        reviewTitle: "אנחנו עוברים על הקמפיין",
        reviewSub: "בודקים שהמבנה, התקציב והמודעות מתאימים לניהול דרך השירות.",
        metaConnected: "חשבון Meta מחובר",
        campaignFound: "הקמפיין נמצא",
        inReview: "בבדיקה",
        nothingToDo: "אין צורך לעשות דבר כרגע.",
        approveBadge: "מחכים לכם",
        approveTitle: "צריך אישור קטן לפני שמתחילים",
        approveSub: "עברנו על הקמפיין וממליצים לעצור מודעה אחת ולהשאיר את התקציב על ₪80 ביום. צריך את האישור שלכם כדי לבצע.",
        viewChange: "לצפייה בשינוי",
        wantToTalk: "אני רוצה לדבר על זה",
        readyTitle: "הכל מוכן",
        readySub: "הקמפיין מחובר ואנחנו מתחילים לעקוב אחריו.",
        goToAccount: "מעבר לחשבון",
      },
      connect: {
        backToStatus: "← חזרה לסטטוס ההקמה",
        title: "חיבור חשבון Meta",
        sub: "צריך לתת לנו גישה לחשבון הפרסום שבו נמצא הקמפיין שננהל.",
        noPassword: "אנחנו לא צריכים את הסיסמה שלכם לפייסבוק.",
        howTitle: "איך עושים את זה",
        steps: [
          "פותחים את הגדרות העסק ב־Meta",
          "מוסיפים את AdPilot כשותף עסקי",
          "נותנים גישה לחשבון הפרסום",
          "אם נדרש, נותנים גישה גם לעמוד הפייסבוק / אינסטגרם",
          "חוזרים לכאן ואנחנו בודקים שהכול מחובר",
        ],
        openMeta: "פתיחת Meta Business Settings ↗",
        businessId: "BUSINESS ID",
        copy: "העתקה",
        copied: "הועתק",
        whenNeeded: "מתי זה נדרש?",
        whenNeededBody: "אם המודעות מוצגות מהעמוד או מהאינסטגרם שלכם, נצטרך גם אותם כדי לפרסם ולעצור מודעות.",
        checkCta: "בדיקת החיבור",
        checking: "בודקים את החיבור…",
        checkingSub: "זה לוקח כמה שניות. אפשר להישאר בעמוד.",
        connectedTitle: "החשבון מחובר",
        adAccount: "חשבון פרסום", fbPage: "עמוד פייסבוק", instagram: "אינסטגרם",
        technical: "פרטים טכניים",
        continue: "המשך",
        missingTitle: "חסרה גישה",
        missingBody: "חשבון הפרסום מחובר, אבל חסרה גישה לעמוד הפייסבוק. בלי גישה לעמוד לא נוכל לפרסם או לעצור מודעות בשמכם. זה תיקון קצר בהגדרות העסק ב־Meta.",
        connected: "מחובר", missing: "חסר",
        howToFix: "איך מתקנים?",
        fixSteps: [
          "בהגדרות העסק ב־Meta עוברים ל״עמודים״.",
          "בוחרים את העמוד ולוחצים על ״שותפים״.",
          "מוסיפים את AdPilot עם הרשאת ניהול מודעות.",
        ],
        recheck: "בדיקה מחדש",
        notVerifiedTitle: "לא הצלחנו לאמת את החיבור",
        notVerifiedBody: "אפשר לנסות שוב או לדבר איתנו ונעבור על זה יחד. הקמפיין שלכם ממשיך לרוץ כרגיל בזמן הזה.",
        retry: "נסה שוב",
      },
      review: {
        title: "אנחנו ממליצים על כמה התאמות לפני שמתחילים",
        sub: "זה הקמפיין שננהל. עברנו עליו וכתבנו מה כדאי לשנות — הכל יבוצע רק אחרי שתאשרו.",
        campaign: "קמפיין WhatsApp", active: "פעיל",
        budget: "תקציב", area: "אזור", ads: "מודעות", goal: "מטרה",
        budgetVal: "₪80 ביום", areaVal: "ראשון לציון והסביבה", adsVal: "4 מודעות", goalVal: "פניות ב־WhatsApp",
        running: "המודעות שרצות",
        keep: "נשארת", pauseRec: "מומלץ לעצור", isNew: "חדשה",
        proposalsTitle: "מה אנחנו מציעים",
        proposals: [
          { t: "לעצור מודעה אחת", d: "המודעה הזאת כמעט לא מביאה פניות לעומת האחרות." },
          { t: "לפשט את מבנה הקמפיין", d: "הקמפיין הקיים מפוצל למספר קבוצות שלא נותנות מספיק מידע בתקציב הנוכחי." },
          { t: "להישאר על ₪80 ביום", d: "התקציב המקסימלי לאחר השינוי: ₪80 ביום." },
        ],
        approveStart: "מאשר להתחיל",
        confirmedTitle: "קיבלנו את האישור",
        confirmedSub: "אנחנו משלימים את ההגדרה ומתחילים לעקוב.",
        backToStatus: "חזרה לסטטוס ההקמה",
      },
      home: {
        title: "הקמפיין שלך",
        navHome: "ראשי", navRecs: "המלצות", navSettings: "עזרה והגדרות",
        periods: { month: "החודש", days7: "7 ימים", prev: "חודש קודם" },
        kpiCpl: "לפנייה", kpiLeads: "פניות", kpiSpend: "הוצאה החודש",
        states: {
          ok: { badge: "פעיל", title: "הכל עובד כרגיל", body: "הקמפיין פעיל ואין כרגע משהו שדורש את תשומת הלב שלך." },
          rec: { badge: "מחכה לך", title: "יש לנו המלצה אחת", body: "מצאנו שינוי שיכול לשפר את הקמפיין ומחכה לאישור שלך.", cta: "לצפייה בהמלצה" },
          collecting: { badge: "אוספים נתונים", title: "רק התחלנו לאסוף נתונים", body: "עדיין מוקדם להסיק מסקנות. אנחנו ממשיכים לעקוב." },
          paused: { badge: "מושהה", title: "הקמפיין כרגע מושהה", body: "הקמפיין מושהה ואינו מוציא תקציב או מביא פניות עד שנחזיר אותו לפעילות. לחידוש הפעילות דברו איתנו.", cta: "" },
          attention: { badge: "צריך טיפול", title: "איבדנו גישה לחשבון Meta", body: "הקמפיין עשוי להמשיך לרוץ, אבל לא נוכל לנהל אותו עד לחיבור מחדש.", cta: "חיבור מחדש" },
          setup: { badge: "בהקמה", title: "אנחנו מקימים את החשבון", body: "החשבון נפתח. אחרי שיחת ההיכרות וחיבור Meta נתחיל לנהל את הקמפיין ותוכלו לראות כאן נתונים.", cta: "לסטטוס ההקמה" },
          // AIC-52: connected + ready, but the customer hasn't built their first
          // campaign yet — distinct from "setup" (still onboarding/connecting).
          createCampaign: { badge: "מוכן להתחיל", title: "בואו ניצור את הקמפיין הראשון שלכם", body: "כמה שאלות קצרות וממליצים לכם על ברירת מחדל בכל שלב — אפשר תמיד לשנות.", cta: "בניית הקמפיין" },
          // AIC-53: built + review-approved, PAUSED on Meta, waiting for the
          // customer's explicit go-live approval — nothing spends until they click.
          readyToLaunch: { badge: "מוכן להפעלה", title: "הקמפיין מוכן — נותר רק לאשר הפעלה", body: "בנינו את הקמפיין והוא עבר בדיקה, אבל הוא עדיין מושהה ולא מוציא כסף. ההפעלה מתבצעת רק באישור שלכם.", cta: "אישור והפעלה" },
          // AIC-39: a not-delivering ad set — distinct from a lost Meta connection.
          delivery: { badge: "צריך טיפול", title: "חלק מהקמפיין לא מתפרסם כרגע", body: "אחת מקבוצות הפרסום נתקלה בבעיה ואינה מציגה מודעות. אנחנו כבר על זה — ניצור קשר אם נצטרך משהו מכם. שאר הקמפיין ממשיך לרוץ.", cta: "" },
        },
        live: {
          vsPrev: "מהתקופה הקודמת",
          noCompare: "אין תקופה קודמת להשוואה",
          noActivity: "עדיין לא בוצעו שינויים בקמפיין.",
          adsActive: "מודעות פעילות",
          perDay: "ביום",
          perMonth: "בחודש",
          none: "—",
          automated: "בוצע אוטומטית",
          byUs: "בוצע על ידינו",
        },
        // AIC-37: opt-in per-audience / per-creative details — collapsed by
        // default, never the landing view.
        details: {
          show: "הצג פירוט",
          hide: "הסתר פירוט",
          empty: "עדיין אין מספיק נתונים לפירוט לפי קהל.",
          audienceCol: "קהל",
          spendCol: "הוצאה",
          leadsCol: "פניות",
          cplCol: "עלות לפנייה",
          creativesCol: "מודעות",
        },
        recWaitingTitle: "המלצה שמחכה לך",
        recWaiting: "כדאי לעצור את אחת המודעות",
        recWaitingReason: "היא הוציאה ₪184 והביאה פנייה אחת בלבד. שתי המודעות האחרות עובדות טוב יותר.",
        viewApprove: "לצפייה ולאישור",
        noActionTitle: "אין כרגע משהו שצריך לעשות",
        noAction: "אנחנו ממשיכים לעקוב אחר הקמפיין.",
        weeklyTitle: "משוב שבועי",
        weeklyQ: "איך היו הפניות השבוע?",
        weeklyCount: "כמה מהפניות שקיבלת השבוע היו רלוונטיות?",
        weeklyLeadsLine: "פניות השבוע",
        weeklyThanksTitle: "קיבלנו, תודה",
        weeklyThanks: "זה עוזר לנו להבין טוב יותר אילו פניות באמת שוות לעסק.",
        weeklyNoLeads: "השבוע עדיין לא התקבלו פניות. אנחנו ממשיכים לעקוב לפני שממליצים על שינוי.",
        recentTitle: "מה קרה לאחרונה", recentAll: "לכל השינויים",
        recent: [
          { d: "12 באוג׳", t: "עצרנו מודעה חלשה לאחר שאישרתם." },
          { d: "5 באוג׳", t: "התקציב עודכן מ־₪70 ל־₪80 ביום." },
          { d: "1 באוג׳", t: "התחיל ניהול הקמפיין." },
        ],
        summaryTitle: "קמפיין WhatsApp",
        sMode: "מצב", sBudget: "תקציב", sAds: "מודעות", sLeads: "פניות לפי שבוע",
        sBudgetVal: "₪80 ביום", sAdsVal: "4 מודעות פעילות", sLeadsVal: "18 סה״כ",
      },
      // Launch gate (AIC-53) — the confirmation before a campaign goes live.
      launch: {
        title: "אישור הפעלת הקמפיין",
        intro: "ברגע שתאשרו, הקמפיין יתחיל לפעול ולהוציא תקציב לפי מה שמופיע כאן. עד אז הוא מושהה ולא מוציא כלום.",
        nameLine: "קמפיין",
        budgetLine: "תקציב יומי",
        maxSpendLine: "הוצאה מקסימלית מוערכת לחודש",
        adsLine: "מודעות",
        whatsappLine: "פניות אל וואטסאפ",
        approveCta: "אישור והפעלה",
        approving: "מפעיל…",
        cancel: "לא עכשיו",
        successTitle: "הקמפיין פעיל",
        successBody: "הקמפיין הופעל ומתחיל לרוץ. נעקוב אחריו ונעדכן כשיהיה משהו ששווה לשנות.",
        failed: "לא הצלחנו להפעיל את הקמפיין כרגע. אפשר לנסות שוב בעוד רגע — שום דבר לא הופעל פעמיים.",
        perMonth: "לחודש",
      },
      recs: {
        title: "המלצות",
        emptyTitle: "אין עדיין המלצות",
        empty: "אנחנו ממשיכים לעקוב אחרי הקמפיין ונעדכן כשיהיה משהו ששווה לשנות.",
        waiting: "מחכה לאישור שלך",
        view: "לצפייה",
        doneTitle: "מה כבר עשינו",
        notSure: "לא בטוחים לגבי המלצה?",
      },
      recDetail: {
        back: "← חזרה להמלצות",
        createdAgo: "נוצרה לפני 2 ימים",
        pauseTitle: "כדאי לעצור את המודעה הזאת",
        whyTitle: "למה אנחנו ממליצים",
        pauseWhy: "המודעה הוציאה ₪184 ב־7 הימים האחרונים והביאה פנייה אחת. שתי המודעות האחרות מביאות פניות במחיר נמוך משמעותית.",
        whatChangesTitle: "מה ישתנה?",
        pauseChanges: ["המודעה הזאת תיעצר.", "הקמפיין ושאר המודעות ימשיכו לפעול.", "התקציב הכולל לא יגדל."],
        incTitle: "כדאי להגדיל מעט את התקציב",
        incWhy: "מחיר הפנייה נמוך מהיעד כבר מספר ימים ואנחנו רואים מקום להגדיל את הפעילות.",
        today: "היום", proposed: "מוצע",
        incFrom: "₪70 ביום", incTo: "₪80 ביום",
        maxImpact: "תוספת מקסימלית של ₪10 ביום.",
        incChange: "התקציב יעבור מ־₪70 ל־₪80 ביום. השינוי מתבצע מיד לאחר האישור.",
        replaceTitle: "הגיע הזמן להחליף מודעה",
        replaceWhy: "הביצועים שלה נחלשו משמעותית בשבוע האחרון.",
        replaceNote: "נבקש ממך קריאייטיב חדש לפני שנבצע שינוי.",
        wantToTalk: "רוצה לדבר על זה?",
        approvedTitle: "אישרתם את השינוי",
        approvedSub: "אנחנו מבצעים אותו עכשיו. נעדכן כאן כשזה יושלם.",
        executedTitle: "השינוי בוצע",
        whatWeDid: "מה נעשה", whenDone: "מתי",
        backToRecs: "חזרה להמלצות",
        dismissedTitle: "בחרתם לא לבצע את השינוי",
        dismissedSub: "הקמפיין ממשיך כרגיל. אם תשנו את דעתכם, אנחנו כאן.",
        expiredTitle: "ההמלצה כבר לא רלוונטית",
        expiredSub: "מאז שיצרנו אותה, ביצועי הקמפיין השתנו. אם נראה שוב מקום לשינוי, נעדכן.",
        failedTitle: "לא הצלחנו לבצע את השינוי",
        failedSub: "לא בוצע שינוי בקמפיין. אנחנו בודקים מה קרה ונחזור אליכם.",
        heldTitle: "השינוי לא בוצע כרגע",
        heldSub: "לא בוצע שינוי בקמפיין. אפשר לנסות שוב מאוחר יותר או לדבר איתנו.",
        unavailableSub: "השירות זמנית אינו זמין לביצוע שינויים. נסו שוב עוד מעט.",
        // Titles + "what changes" keyed by recommendation type (live data path).
        titles: {
          pause_creative: "כדאי לעצור את המודעה הזאת",
          pause_adset: "כדאי לעצור קהל שמבזבז תקציב",
          increase_budget: "כדאי להגדיל מעט את התקציב",
          decrease_budget: "כדאי להוריד זמנית את התקציב",
          replace_creative: "כדאי להחליף את הקריאייטיב",
          no_action: "אין כרגע שינוי מומלץ",
        },
        changesBudget: "השינוי מתבצע מיד לאחר האישור.",
        changesReplace: "החלפת הקריאייטיב מתבצעת יחד עם הצוות שלנו — ניצור קשר להמשך.",
        changesAudience: "הקהל הזה ייעצר; התקציב יופנה לקהל שמביא תוצאות טובות יותר. סך התקציב לא יגדל.",
        maxImpactPrefix: "תוספת מקסימלית של",
      },
      settings: {
        title: "עזרה והגדרות",
        supportTitle: "צריכים עזרה?",
        support: "אפשר לדבר איתנו בוואטסאפ או לקבוע שיחה.",
        bookCall: "קביעת שיחה",
        budgetTitle: "תקציב פרסום",
        budgetReq: "בקשה לשינוי תקציב",
        budgetNote: "זהו התקציב של Meta ואינו כולל את דמי השירות.",
        metaTitle: "Meta",
        checkConn: "בדיקת חיבור",
        planTitle: "המסלול שלך",
        planLine: "ניהול קמפיין אחד",
        setupPaid: "ההקמה שולמה",
        nextCharge: "החיוב הבא", nextChargeVal: "1 בספטמבר 2026",
        payMethod: "אמצעי תשלום", payMethodVal: "Visa •••• 4417",
        payMethodManual: "חיוב ידני מול הצוות",
        setupPending: "ההקמה בתשלום",
        noSubTitle: "אין מנוי פעיל",
        noSubNote: "זהו חשבון ניהול פנימי. פרטי המסלול יופיעו כאן לאחר הצטרפות.",
        managePay: "ניהול תשלום",
        budgetReqSent: "בקשתך התקבלה. ניצור איתך קשר בקרוב.",
        checking: "בודקים את החיבור…",
        connOk: "החיבור תקין",
        connProblem: "יש בעיה בחיבור — נחזור אליך.",
        pwCurrent: "סיסמה נוכחית", pwNew: "סיסמה חדשה (לפחות 8 תווים)",
        pwSave: "עדכון סיסמה", pwCancel: "ביטול",
        pwDone: "הסיסמה עודכנה.",
        pwWrong: "הסיסמה הנוכחית שגויה.",
        pwTooShort: "הסיסמה החדשה חייבת להכיל לפחות 8 תווים.",
        accountTitle: "החשבון",
        nameLabel: "שם", emailLabel: "אימייל", changePw: "שינוי סיסמה",
        cancelNote: "ביטול השירות מתבצע בשיחה איתנו, כדי שנוכל לסגור נכון את הקמפיין ב־Meta.",
        cancelLink: "דברו איתנו על ביטול",
      },
      mock: { userName: "לילך ברקוביץ'", userInitials: "לב", email: "lilach@studio.co.il", businessId: "418 552 907 431" },
    },

    // Connection health (AIC-5). Every non-ok state shows the same plain-Hebrew
    // reconnect message — the customer never sees Meta jargon like "revoked",
    // "invalid token", or "OAuth". The server sends the access_health value; the
    // client maps it to copy here.
    connection: {
      needsAttentionTitle: "חסרה לנו הרשאה לחשבון הפרסום",
      needsAttentionBody:
        "כדי שנוכל להמשיך לנהל את הקמפיין, צריך לחבר מחדש את חשבון הפרסום.",
      reconnectCta: "התחברות מחדש",
      healthyStatus: "החיבור לחשבון הפרסום תקין",
    },

    // Guided campaign builder (AIC-52). The server validates and returns
    // error CODES only (see shared/creative-handling.ts); the actual Hebrew
    // shown to the customer lives here. Rationale text for each recommended
    // default is NOT duplicated here — it comes straight from
    // shared/recommended-defaults.ts (the single source of truth AIC-49 set
    // up), read directly by the step components.
    builder: {
      eyebrow: "קמפיין חדש",
      title: "בניית הקמפיין הראשון שלכם",
      recommended: "מומלץ",
      next: "הבא",
      back: "חזרה",
      stepNames: ["מטרה", "וואטסאפ", "תקציב", "קטגוריה מיוחדת", "קהל", "מיקומים", "מודעות", "סיכום"],
      notReadyTitle: "עוד לא מוכנים להתחיל",
      notReadyBody: "צריך קודם לחבר חשבון פרסום ועמוד פעילים ב-Meta, או שכבר יש לכם קמפיין מנוהל.",
      backToAccount: "לדף הראשי",
      unavailable: "יצירת קמפיינים לא זמינה כרגע. נסו שוב בעוד כמה דקות.",

      goal: {
        title: "המטרה של הקמפיין",
        body: "נאסוף פניות דרך וואטסאפ — הדרך הכי טבעית ללקוחות בישראל ליצור איתכם קשר ישירות מהמודעה.",
        objectiveLabel: "יעד הקמפיין",
        objectiveValue: "פניות לוואטסאפ",
        fixedNote: "הגדרות הרכש (Auction) קבועות בשלב הזה ולא מוצגות כבחירה.",
      },
      whatsapp: {
        title: "מספר וואטסאפ",
        body: "לקוחות שילחצו על המודעה ייצרו איתכם קשר במספר הזה.",
        label: "מספר וואטסאפ, עם קידומת מדינה",
        placeholder: "972501234567",
        invalid: "מספר לא תקין — רק ספרות, כולל קידומת מדינה (למשל 972501234567).",
      },
      budget: {
        title: "תקציב יומי",
        label: "תקציב יומי (₪)",
        invalid: "התקציב חייב להיות מספר חיובי.",
        rationale:
          "תקציב של כ־₪40 ליום נותן למנוע מספיק נתונים תוך כשבוע כדי להתחיל להשוות מודעות ולזהות מה מביא פניות בעלות טובה. אפשר להתחיל נמוך יותר ולהעלות בהמשך — זו נקודת פתיחה, לא מספר קבוע.",
      },
      specialCategory: {
        title: "קטגוריה מיוחדת",
        question: "האם העסק שלכם עוסק באשראי, תעסוקה/גיוס עובדים, נדל\"ן/דיור, או נושאים חברתיים/פוליטיים?",
        options: {
          NONE: "לא",
          CREDIT: "אשראי",
          EMPLOYMENT: "תעסוקה / גיוס עובדים",
          HOUSING: "נדל\"ן / דיור",
          ISSUES_ELECTIONS_POLITICS: "נושאים חברתיים / פוליטיים",
        },
      },
      audience: {
        title: "קהל היעד",
        // Business type drives the age/gender defaults — shown as an editable
        // control so the assumption is visible and correctable, not silently
        // read from an operator-typed field the customer never sees.
        businessTypeLabel: "סוג העסק",
        businessTypeHint: "לפי מה שסיפרתם לנו. לא מדויק? אפשר לשנות כאן.",
        businessTypes: {
          beautician: "יופי וטיפוח",
          fitness: "כושר ואימונים",
          tutor: "הוראה פרטית",
          restaurant: "מסעדנות ואוכל",
          home_services: "שירותים בבית (אינסטלציה, חשמל וכו')",
          retail: "חנות / קמעונאות",
          health_wellness: "בריאות ורווחה",
          professional_services: "שירותים מקצועיים",
          real_estate: "נדל\"ן",
          other: "אחר",
        },
        ageMinLabel: "גיל מינימום",
        ageMaxLabel: "גיל מקסימום",
        genderLabel: "מגדר",
        genderOptions: { all: "הכל", male: "גברים", female: "נשים" },
        // In P0 the campaign targets all of Israel by age + gender. Real
        // location/radius targeting is a separate future step (AIC-54) — so we
        // say that plainly rather than showing a radius control that does nothing.
        geoNote: "בשלב הזה הקמפיין מטרגט את כל ישראל, לפי גיל ומגדר. טירגוט לפי אזור או רדיוס מהעסק יתווסף בהמשך.",
        // Keyed by BusinessCategory (shared/recommended-defaults.ts) — every
        // key there must have a match here, kept in sync manually since
        // strings.ts stays free of a runtime dependency on @aic/shared. These
        // justify the age/gender recommendation only — NOT a local radius,
        // which P0 doesn't apply (see geoNote).
        categoryRationale: {
          beautician: "בעסקי יופי וטיפוח, נשים בגילי 18–45 הן בדרך כלל הקהל הרלוונטי ביותר.",
          fitness: "לכושר ואימונים מתאים קהל רחב משני המגדרים, בעיקר בגילי 20–45.",
          tutor: "בהוראה פרטית ההורים או התלמידים הבוגרים הם מקבלי ההחלטה — קהל רחב יחסית משני המגדרים.",
          restaurant: "מסעדות ובתי קפה פונים לקהל רחב מאוד — כל המגדרים וטווח גילים רחב.",
          home_services: "לשירותים בבית (אינסטלציה, חשמל, ניקיון) מתאים קהל בוגר רחב משני המגדרים.",
          retail: "לחנות מקומית מתאים קהל רחב — כל המגדרים וטווח גילים בינוני.",
          health_wellness: "טיפולי בריאות ורווחה מושכים קהל בוגר רחב יחסית.",
          professional_services: "לשירותים מקצועיים (ייעוץ, ראיית חשבון וכו') מתאים קהל בוגר, כל המגדרים.",
          real_estate: "נדל\"ן פונה לקהל בוגר רחב.",
          other: "אין לנו עדיין המלצה ספציפית לתחום הזה — התחלנו בטווח רחב שאפשר לצמצם לפי מה שתדעו על הלקוחות שלכם.",
        },
      },
      placements: {
        title: "מיקומים",
        body: "המיקומים נקבעים אוטומטית (Advantage+): מטא מציגה את המודעות בפיד, בסטוריז ובכל מקום שבו יש סיכוי טוב לפנייה, ומחפשת את העלות הזולה ביותר לכל פנייה.",
        // Presented as a FIXED choice (like the goal step), not a badged
        // recommendation — there's no code path to narrow placements in P0, so
        // we don't imply the customer has a lever they don't.
        fixedNote: "בשלב הזה המיקומים קבועים על אוטומטי ולא מוצגים כבחירה — זו בדרך כלל הגישה שנותנת את העלות הטובה ביותר לפנייה.",
      },
      creatives: {
        title: "מודעות",
        body: "אפשר להעלות תוכן חדש או לבחור פוסט קיים מהעמוד המחובר. מומלץ 3–5 מודעות נפרדות כדי שנוכל להשוות מה עובד הכי טוב.",
        responsibilityNotice:
          "התוכן שאתם מעלים (תמונות, טקסט, הבטחות) הוא באחריותכם — כולל דיוק ועמידה בדרישות החוק והמדיניות של מטא. אנחנו לא בודקים או עורכים את התוכן.",
        uploadTab: "העלאת תוכן",
        postTab: "פוסט קיים",
        adTitle: "מודעה",
        addAd: "הוספת מודעה",
        removeAd: "הסרה",
        nameLabel: "שם פנימי למודעה",
        headlineLabel: "כותרת",
        headlinePlaceholder: "מבצע קיץ",
        primaryTextLabel: "טקסט ראשי",
        primaryTextPlaceholder: "20% הנחה על הטיפול הראשון",
        chooseFile: "בחירת קובץ",
        uploading: "מעלה…",
        noPosts: "לא נמצאו פוסטים בעמוד המחובר.",
        loadingPosts: "טוען פוסטים…",
        createAdCta: "יצירת המודעה",
        creatingAd: "יוצר…",
        adCreated: "המודעה נוצרה",
        countHint: "מומלץ 3–5 מודעות נפרדות",
      },
      review: {
        title: "סיכום לפני יצירה",
        body: "כל מה שנוצר עכשיו יהיה במצב מושהה — לא יוצא כסף עד שתאשרו את ההפעלה בנפרד.",
        goalLine: "יעד",
        whatsappLine: "וואטסאפ",
        budgetLine: "תקציב יומי",
        businessLine: "סוג העסק",
        audienceLine: "קהל",
        placementsLine: "מיקומים",
        placementsValue: "אוטומטי (Advantage+)",
        geoValue: "כל ישראל",
        adsLine: "מודעות",
        createCta: "יצירת הקמפיין (מושהה)",
        creating: "יוצר…",
        successTitle: "הקמפיין נוצר במצב מושהה",
        successBody: "בשלב הבא נעביר אותו בבדיקה ותאשרו את ההפעלה מהדף הראשי.",
        goHome: "למעבר לדף הראשי",
        errorGeneric: "משהו השתבש ביצירת הקמפיין. אפשר לנסות שוב — מה שכבר נוצר לא ייווצר פעמיים.",
      },

      creativeErrors: {
        missing_media: "צריך להעלות תמונה/וידאו או לבחור פוסט קיים לפני שממשיכים.",
        missing_headline: "חסרה כותרת למודעה.",
        headline_too_long: "הכותרת ארוכה מדי — היא עלולה להיחתך בחלק מהמיקומים.",
        missing_primary_text: "חסר טקסט ראשי למודעה.",
        primary_text_too_long: "הטקסט הראשי ארוך מדי.",
      },
    },

    // Add content to an existing campaign (AIC-63) — the everyday management
    // action, distinct from the builder (first campaign only).
    additions: {
      navLabel: "הוספת תוכן",
      eyebrow: "הקמפיין הקיים שלכם",
      title: "הוספת תוכן לקמפיין",
      notReadyTitle: "עוד אין קמפיין להוסיף לו תוכן",
      notReadyBody: "צריך קודם ליצור את הקמפיין הראשון שלכם.",
      goToBuilder: "ליצירת הקמפיין",
      unavailable: "הוספת תוכן לא זמינה כרגע. נסו שוב בעוד כמה דקות.",
      modeAd: "הוספת מודעה",
      modeAdSet: "הוספת קבוצת מודעות",

      // add-ad mode
      pickAdSetTitle: "לאיזו קבוצת מודעות?",
      pickAdSetLoading: "טוען קבוצות מודעות…",
      noAdSets: "לא נמצאו קבוצות מודעות בקמפיין.",
      adSetPaused: "מושהית",
      adsTitle: "המודעה",

      // add-ad-set mode
      adSetNameLabel: "שם פנימי לקבוצת המודעות",
      adSetNamePlaceholder: "למשל: נשים 35-55",

      submitAdCta: "הוספת המודעה (מושהית)",
      submitAdSetCta: "הוספת קבוצת המודעות (מושהית)",
      submitting: "מוסיף…",
      submitSuccessTitle: "נוסף במצב מושהה",
      submitSuccessBody: "מחכה לאישור שלכם למטה כדי להתחיל לרוץ.",
      submitAnother: "הוספת עוד",
      submitError: "משהו השתבש בהוספה. אפשר לנסות שוב — מה שכבר נוצר לא ייווצר פעמיים.",

      pendingTitle: "ממתין לאישור שלכם",
      pendingEmpty: "אין כרגע תוכן שממתין לאישור.",
      pendingKindAd: "מודעה חדשה",
      pendingKindAdSet: "קבוצת מודעות חדשה",
      approveCta: "אישור והפעלה",
      approving: "מפעיל…",
      approveError: "ההפעלה נכשלה. אפשר לנסות שוב.",
    },
  },
} as const;

// Map a connection's access_health to what the customer sees. Anything but "ok"
// is the same reconnect prompt — the distinction between revoked/invalid/
// needs_reconnect is internal only.
export function connectionMessage(
  accessHealth: "ok" | "revoked" | "invalid" | "needs_reconnect",
): { healthy: boolean; title: string; body?: string; cta?: string } {
  const c = strings.he.connection;
  if (accessHealth === "ok") {
    return { healthy: true, title: c.healthyStatus };
  }
  return {
    healthy: false,
    title: c.needsAttentionTitle,
    body: c.needsAttentionBody,
    cta: c.reconnectCta,
  };
}

// Map a creative-validation error code (shared/creative-handling.ts) to its
// Hebrew message. Codes cross the API untranslated; only the client displays copy.
export function creativeValidationMessage(code: keyof typeof strings.he.builder.creativeErrors): string {
  return strings.he.builder.creativeErrors[code];
}
